# for ubuntu
ubuntu:
	sudo apt-get install python-pygame

# if you want same version of modules with me
getmine:
	sudo apt-get install python-pip
	pip install -r requirement.txt	

# else
tellthem:
	echo "Require python pygame module installed."

all: tellthem

